export const ADD_PLACE = 'ADD_PLACE'
export const DELETE_PLACE = 'DELETE_PLACE'

export const TRY_AUTH = 'TRY_AUTH'

export const UI_START_LOADING = 'UI_START_LOADING'
export const UI_COMPLETE_LOADING = 'UI_COMPLETE_LOADING'